### ISSUE TITLE
Rotator fails to compile with cotroller-runtime 0.18.1

### ISSUE THREAD

**Issue by zbindenren** [open-policy-agent/cert-controller#207]
If you try you get the following error:

```
 github.com/open-policy-agent/cert-controller/pkg/rotator
.go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.10.1/pkg/rotator/rotator.go:703:24: not enough arguments in call to source.Kind
	have ("sigs.k8s.io/controller-runtime/pkg/cache".Cache, *"k8s.io/api/core/v1".Secret)
	want ("sigs.k8s.io/controller-runtime/pkg/cache".Cache, T, handler.TypedEventHandler[T], ...predicate.TypedPredicate[T])
.go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.10.1/pkg/rotator/rotator.go:704:3: too many arguments in call to c.Watch
	have (source.SyncingSource, *handler.TypedEnqueueRequestForObject[client.Object])
	want (source.Source)
.go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.10.1/pkg/rotator/rotator.go:714:25: not enough arguments in call to source.Kind
	have ("sigs.k8s.io/controller-runtime/pkg/cache".Cache, *unstructured.Unstructured)
	want ("sigs.k8s.io/controller-runtime/pkg/cache".Cache, T, handler.TypedEventHandler[T], ...predicate.TypedPredicate[T])
.go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.10.1/pkg/rotator/rotator.go:715:4: too many arguments in call to c.Watch
	have (source.SyncingSource, handler.EventHandler)
	want (source.Source)
```

**Comment by kerthcet** [comment]
+1 we use 0.18.2.

**Comment by yangzuo0621** [comment]
The master branch has been updated to v0.18.3 for sigs.k8s.io/controller-runtime, but a release for this version has not been made yet.

**Comment by danielvegamyhre** [comment]
Any estimate for when this will be done? This is blocking our project from upgrading to k8s api v0.30 since it requires controller-runtime v0.18+, which is not compatible with cert-controller's latest release.

**Comment by sozercan** [comment]
Sorry for the delay. We can cut a new release. @ritazh @maxsmythe any objections?

**Comment by ritazh** [comment]
> Sorry for the delay. We can cut a new release. @ritazh @maxsmythe any objections?

sgtm

**Comment by sozercan** [comment]
https://github.com/open-policy-agent/cert-controller/releases/tag/v0.11.0 is available now!

**Comment by kerthcet** [comment]
Awesome, thanks!

**Comment by kerthcet** [comment]
Wait a minute, let me check again.

**Comment by kerthcet** [comment]
Yeah, that's my mistake, exactly got fixed. Sorry for the misleading.
